import { useEffect, useState } from 'react';
import { Activity, AlertTriangle, CheckCircle2, Database, Download, HardDrive, Mail, MessageCircle, RefreshCw, ShieldCheck, Upload, Server, Clock3 } from 'lucide-react';
import client, { apiErrorMessage } from '../../api/client';
import { SectionHeader, Badge } from '../../components/Shared';
import { useToast } from '../../context/ToastContext';

const moneySize = (n) => n == null ? '—' : `${(Number(n) / 1024 / 1024).toFixed(2)} Mo`;
function Status({ ok, label }) { return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-bold ${ok ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}><span className={`h-1.5 w-1.5 rounded-full ${ok ? 'bg-emerald-500' : 'bg-amber-500'}`} />{label}</span>; }
function Card({ title, icon: Icon, children }) { return <section className="card"><div className="flex items-center gap-2 mb-4"><Icon size={17} className="text-brand-700"/><h3 className="font-display font-extrabold text-slate-900">{title}</h3></div>{children}</section>; }

export default function Systeme() {
  const [status,setStatus]=useState(null), [comm,setComm]=useState(null), [backups,setBackups]=useState([]), [loading,setLoading]=useState(true), [busy,setBusy]=useState(false), [file,setFile]=useState(null), [confirmation,setConfirmation]=useState('');
  const toast = useToast();
  const load=async()=>{setLoading(true);try{const [a,b,c]=await Promise.all([client.get('/system/status'),client.get('/system/communication'),client.get('/system/backups')]);setStatus(a.data);setComm(b.data);setBackups(c.data||[]);}catch(e){toast?.error?.(apiErrorMessage(e));}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const backup=async()=>{setBusy(true);try{await client.post('/system/backup');toast?.success?.('Sauvegarde créée avec succès.');await load();}catch(e){toast?.error?.(apiErrorMessage(e));}finally{setBusy(false);}};
  const restore=async(e)=>{e.preventDefault();if(!file)return toast?.error?.('Sélectionnez un fichier SQL.');if(confirmation!=='RESTAURER COPEC')return toast?.error?.('Saisissez exactement RESTAURER COPEC.');if(!window.confirm('La restauration peut remplacer les données actuelles. Continuer ?'))return;const fd=new FormData();fd.append('backup',file);fd.append('confirmation',confirmation);setBusy(true);try{await client.post('/system/restore',fd,{headers:{'Content-Type':'multipart/form-data'}});toast?.success?.('Restauration terminée.');setFile(null);setConfirmation('');await load();}catch(e){toast?.error?.(apiErrorMessage(e));}finally{setBusy(false);}};
  if(loading&&!status)return <div className="page-shell"><SectionHeader title="Système & sécurité" subtitle="Observabilité, communication et sauvegardes"/><div className="card animate-pulse h-64"/></div>;
  return <div className="page-shell space-y-6 animate-fadein">
    <SectionHeader title="Système & sécurité" subtitle="Mode de déploiement, santé des services, communication et protection des données" action={<button className="btn-secondary" onClick={load}><RefreshCw size={15}/> Actualiser</button>} />
    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
      <div className="card"><p className="section-kicker">Mode</p><div className="flex items-center gap-3 mt-2"><ShieldCheck size={22} className="text-brand-700"/><strong className="font-display text-xl">{status?.providers?.mode === 'demo' ? 'DÉMO' : 'PRODUCTION'}</strong></div><p className="text-xs text-slate-500 mt-2">Les quotas DEMO évitent les envois massifs pendant le stage.</p></div>
      <div className="card"><p className="section-kicker">Base de données</p><div className="mt-2"><Status ok={status?.database?.status==='ok'} label={status?.database?.status==='ok' ? `Opérationnelle · ${status.database.latency_ms} ms` : 'Indisponible'} /></div></div>
      <div className="card"><p className="section-kicker">Dernière sauvegarde</p><div className="flex items-center gap-2 mt-2"><Clock3 size={18}/><strong>{status?.last_backup?.created_at ? new Date(status.last_backup.created_at).toLocaleString('fr-FR') : 'Aucune'}</strong></div></div>
    </div>
    <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
      <Card title="Santé des services" icon={Activity}><div className="space-y-3 text-sm"><div className="flex justify-between"><span className="flex gap-2 items-center"><Database size={15}/>API / DB</span><Status ok={status?.database?.status==='ok'} label={status?.database?.status==='ok'?'OK':'Erreur'}/></div><div className="flex justify-between"><span className="flex gap-2 items-center"><HardDrive size={15}/>Stockage uploads</span><Status ok={Boolean(status?.storage?.exists&&status?.storage?.writable)} label={status?.storage?.exists&&status?.storage?.writable?'OK':'À vérifier'}/></div><div className="flex justify-between"><span className="flex gap-2 items-center"><HardDrive size={15}/>Stockage backups</span><Status ok={Boolean(status?.backup_storage?.exists&&status?.backup_storage?.writable)} label={status?.backup_storage?.exists&&status?.backup_storage?.writable?'OK':'À vérifier'}/></div><div className="flex justify-between"><span className="flex gap-2 items-center"><Mail size={15}/>Email</span><Status ok={Boolean(status?.providers?.email?.configured)} label={status?.providers?.email?.configured?'Configuré':'Non configuré'}/></div><div className="flex justify-between"><span className="flex gap-2 items-center"><MessageCircle size={15}/>WhatsApp</span><Status ok={Boolean(status?.providers?.whatsapp?.configured)} label={status?.providers?.whatsapp?.configured?'Configuré':'Non configuré'}/></div></div></Card>
      <Card title="Communication Center" icon={MessageCircle}><div className="grid grid-cols-2 gap-3 mb-4"><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Email DEMO / jour</p><strong>{comm?.usage?.filter(x=>x.channel==='email'&&new Date(x.usage_date).toDateString()===new Date().toDateString())[0]?.attempts||0} / {import.meta.env.VITE_DEMO_EMAIL_DAILY_LIMIT||20}</strong></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">WhatsApp DEMO / jour</p><strong>{comm?.usage?.filter(x=>x.channel==='whatsapp'&&new Date(x.usage_date).toDateString()===new Date().toDateString())[0]?.attempts||0} / {import.meta.env.VITE_DEMO_WHATSAPP_DAILY_LIMIT||5}</strong></div></div><div className="space-y-2 max-h-44 overflow-auto">{(comm?.deliveries||[]).map((x,i)=><div key={i} className="flex justify-between text-xs border-b border-slate-100 pb-2"><span>{x.channel} · {x.status}</span><strong>{x.total}</strong></div>)}{!(comm?.deliveries||[]).length&&<p className="text-sm text-slate-400">Aucune livraison sur les 30 derniers jours.</p>}</div></Card>
    </div>
    <Card title="Sauvegarde & restauration" icon={Server}><div className="flex flex-col lg:flex-row gap-5"><div className="flex-1"><p className="text-sm text-slate-600">Une sauvegarde PostgreSQL complète peut être créée manuellement. En production, <code>BACKUP_AUTO=true</code> active la sauvegarde quotidienne et la rétention.</p><button className="btn-primary mt-4" disabled={busy} onClick={backup}><Download size={15}/>{busy?'Traitement…':'Créer une sauvegarde maintenant'}</button></div><form onSubmit={restore} className="flex-1 rounded-2xl border border-red-100 bg-red-50/50 p-4"><div className="flex items-center gap-2 text-red-800 font-bold"><AlertTriangle size={16}/>Restauration administrateur</div><p className="text-xs text-red-700 mt-1">Désactivée par défaut. Elle nécessite <code>ALLOW_DB_RESTORE=true</code> côté serveur et la confirmation exacte ci-dessous.</p><input className="input mt-3" type="file" accept=".sql" onChange={e=>setFile(e.target.files?.[0]||null)}/><input className="input mt-2" placeholder="RESTAURER COPEC" value={confirmation} onChange={e=>setConfirmation(e.target.value)}/><button className="btn-secondary mt-3" disabled={busy||!file}><Upload size={15}/>Restaurer</button></form></div><div className="mt-6 overflow-x-auto"><table className="data-table w-full"><thead><tr><th>Fichier</th><th>Taille</th><th>Checksum</th><th>Statut</th><th>Date</th><th/></tr></thead><tbody>{backups.map(b=><tr key={b.id}><td className="font-medium">{b.filename}</td><td>{moneySize(b.size_bytes)}</td><td className="font-mono text-[10px]">{b.checksum_sha256?.slice(0,16)}…</td><td><Badge tone={b.status==='success'?'green':'red'}>{b.status}</Badge></td><td>{new Date(b.created_at).toLocaleString('fr-FR')}</td><td>{b.status==='success'&&<button className="btn-icon" title="Télécharger" onClick={async()=>{try{const r=await client.get(`/system/download-backup/${b.id}`,{responseType:'blob'});const u=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=u;a.download=b.filename;a.click();URL.revokeObjectURL(u);}catch(e){toast?.error?.(apiErrorMessage(e));}}}><Download size={15}/></button>}</td></tr>)}{!backups.length&&<tr><td colSpan="6" className="text-center text-slate-400 py-8">Aucune sauvegarde enregistrée.</td></tr>}</tbody></table></div></Card>
  </div>;
}
