-- ============================================================
-- BASE DE DONNÉES : COPEC ISAHA — GESTION ÉCOLE
-- STRUCTURE UNIQUEMENT (tables, contraintes, index, triggers, fonctions)
-- Aucune donnée ici — voir seed.sql pour les données de démonstration.
-- PostgreSQL 14+
-- ============================================================
-- Ce fichier est AUTONOME : il contient déjà toute la structure finale,
-- y compris ce qui provenait auparavant de plusieurs migrations
-- (désormais supprimées, leur contenu étant intégré directement ici) :
--   - vérification selfie (2 facteurs)    -> colonnes selfie_* sur utilisateur
--                                             et pointage_enseignant (ci-dessous)
--   - rôles agent simplifiés              -> agent.role_agent limité directement
--                                             à ('secretaire','economie','surveillant')
--   - index unique partiel sur la paie    -> uk_paie_mois_annee_actif (voir plus bas)
--   - sécurité / récupération mot de passe -> password_reset_token, security_event, security_version
--   - communications / sauvegardes       -> notification_delivery, communication_usage, system_backup
-- Un simple `psql -f database/schema.sql` (base neuve) suffit donc à obtenir
-- toute la structure finale. Les anciennes migrations sont désormais intégrées ici.
-- ============================================================
-- Usage :
--   psql "$DATABASE_URL" -f database/schema.sql
--   psql "$DATABASE_URL" -f database/seed.sql      (optionnel, données de démo)
-- ============================================================

BEGIN;

-- Tables V10 : doivent aussi être supprimées lors d'une réinstallation complète.
-- Elles avaient été oubliées dans l'ancienne liste DROP, ce qui provoquait
-- `relation "password_reset_token" already exists` sur un Neon déjà initialisé.
DROP TABLE IF EXISTS system_backup CASCADE;
DROP TABLE IF EXISTS communication_usage CASCADE;
DROP TABLE IF EXISTS security_event CASCADE;
DROP TABLE IF EXISTS notification_delivery CASCADE;
DROP TABLE IF EXISTS password_reset_token CASCADE;
DROP TABLE IF EXISTS parametre_ecole CASCADE;
DROP TABLE IF EXISTS assistant_conversation CASCADE;
DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS message_parent CASCADE;
DROP TABLE IF EXISTS mouvement_caisse CASCADE;
DROP TABLE IF EXISTS cloture_caisse CASCADE;
DROP TABLE IF EXISTS compteur_recu CASCADE;
DROP TABLE IF EXISTS caisse CASCADE;
DROP TABLE IF EXISTS depense CASCADE;
DROP TABLE IF EXISTS categorie_depense CASCADE;
DROP TABLE IF EXISTS sortie_eleve CASCADE;
DROP TABLE IF EXISTS transfert_eleve CASCADE;
DROP TABLE IF EXISTS discipline CASCADE;
DROP TABLE IF EXISTS resultat_examen CASCADE;
DROP TABLE IF EXISTS examen_matiere CASCADE;
DROP TABLE IF EXISTS examen CASCADE;
DROP TABLE IF EXISTS bimestre CASCADE;
DROP TABLE IF EXISTS niveau CASCADE;
DROP TABLE IF EXISTS cycle CASCADE;
DROP TABLE IF EXISTS parent CASCADE;
DROP TABLE IF EXISTS eleve_parent CASCADE;
DROP TABLE IF EXISTS actualite CASCADE;
DROP TABLE IF EXISTS envoi_rapport_detail CASCADE;
DROP TABLE IF EXISTS envoi_rapport CASCADE;
DROP TABLE IF EXISTS notification CASCADE;
DROP TABLE IF EXISTS document_eleve CASCADE;
DROP TABLE IF EXISTS certificat_scolarite CASCADE;
DROP TABLE IF EXISTS relance_impaye CASCADE;
DROP TABLE IF EXISTS paiement CASCADE;
DROP TABLE IF EXISTS frais_scolaire CASCADE;
DROP TABLE IF EXISTS tarif_frais CASCADE;
DROP TABLE IF EXISTS paie CASCADE;
DROP TABLE IF EXISTS controle_paie CASCADE;
DROP TABLE IF EXISTS salaire_enseignant CASCADE;
DROP TABLE IF EXISTS absence_eleve CASCADE;
DROP TABLE IF EXISTS absence_enseignant CASCADE;
DROP TABLE IF EXISTS devoir CASCADE;
DROP TABLE IF EXISTS bulletin_matiere CASCADE;
DROP TABLE IF EXISTS bulletin CASCADE;
DROP TABLE IF EXISTS note CASCADE;
DROP TABLE IF EXISTS pointage_eleve CASCADE;
DROP TABLE IF EXISTS pointage_enseignant CASCADE;
DROP TABLE IF EXISTS emploi_du_temps CASCADE;
DROP TABLE IF EXISTS salle CASCADE;
DROP TABLE IF EXISTS enseignant_matiere_classe CASCADE;
DROP TABLE IF EXISTS enseignant_matiere CASCADE;
DROP TABLE IF EXISTS inscription CASCADE;
DROP TABLE IF EXISTS eleve CASCADE;
DROP TABLE IF EXISTS classe_matiere CASCADE;
DROP TABLE IF EXISTS classe CASCADE;
DROP TABLE IF EXISTS matiere CASCADE;
DROP TABLE IF EXISTS annee_scolaire CASCADE;
DROP TABLE IF EXISTS agent CASCADE;
DROP TABLE IF EXISTS visiteur CASCADE;
DROP TABLE IF EXISTS role_permission CASCADE;
DROP TABLE IF EXISTS permission CASCADE;
DROP TABLE IF EXISTS utilisateur CASCADE;

-- TABLE utilisateur
CREATE TABLE utilisateur (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100),
    email VARCHAR(150) UNIQUE NOT NULL,
    mot_de_passe VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('admin', 'enseignant')),
    telephone VARCHAR(30),
    adresse VARCHAR(255),
    photo_url TEXT,
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    security_version INTEGER NOT NULL DEFAULT 0,

    -- Vérification 2 facteurs par selfie
    selfie_reference_url TEXT,
    selfie_descriptor JSONB,
    compte_confirme BOOLEAN NOT NULL DEFAULT FALSE,
    selfie_confirmee_le TIMESTAMPTZ,
    selfie_reset_par_id INT REFERENCES utilisateur(id) ON DELETE SET NULL,
    selfie_reset_le TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- TABLE agent
CREATE TABLE agent (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100),
    email VARCHAR(150) UNIQUE NOT NULL,
    mot_de_passe VARCHAR(255) NOT NULL,
    role_agent VARCHAR(50) NOT NULL CHECK (role_agent IN ('secretaire', 'economie', 'surveillant', 'accueil')),
    telephone VARCHAR(30),
    adresse VARCHAR(255),
    photo_url TEXT,
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    security_version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- TABLE permission / role_permission
CREATE TABLE permission (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL UNIQUE,
    libelle VARCHAR(200) NOT NULL,
    module VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE role_permission (
    role VARCHAR(50) NOT NULL,
    permission_id INT NOT NULL REFERENCES permission(id) ON DELETE CASCADE,
    PRIMARY KEY (role, permission_id)
);
CREATE INDEX idx_role_permission_role ON role_permission(role);

-- TABLE annee_scolaire
CREATE TABLE annee_scolaire (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle VARCHAR(20) NOT NULL UNIQUE,
    date_debut DATE NOT NULL,
    date_fin DATE NOT NULL,
    actif BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_dates_annee CHECK (date_fin > date_debut)
);

-- TABLE parametre_ecole
-- Ligne unique (id = 1) : identité de l'établissement + branding utilisés dans
-- l'en-tête de l'appli, les bulletins/reçus PDF et les rapports envoyés aux parents.
CREATE TABLE parametre_ecole (
    id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    nom_ecole VARCHAR(150) NOT NULL DEFAULT 'COPEC ISAHA',
    slogan VARCHAR(200),
    adresse VARCHAR(255),
    telephone VARCHAR(30),
    email VARCHAR(150),
    logo_url TEXT,
    couleur_principale VARCHAR(20) NOT NULL DEFAULT '#1b3c62',
    couleur_accent VARCHAR(20) NOT NULL DEFAULT '#d99a3f',
    devise VARCHAR(10) NOT NULL DEFAULT 'Ar',
    -- jour_echeance_defaut : jour du mois (1-28) utilisé pour calculer automatiquement la
    -- date d'échéance d'un frais récurrent (écolage) lors de POST /finance/tarifs/generer,
    -- quand le tarif lui-même n'a pas de jour_echeance spécifique (voir tarif_frais). Évite
    -- à l'économe de ressaisir une date_echeance à chaque génération mensuelle.
    jour_echeance_defaut INT NOT NULL DEFAULT 10 CHECK (jour_echeance_defaut BETWEEN 1 AND 28),
    -- relance_seuil_jours : nombre de jours après la date_echeance à partir duquel un frais
    -- impayé/partiel devient éligible à une relance automatique (voir services/relanceService.js).
    relance_seuil_jours INT NOT NULL DEFAULT 7 CHECK (relance_seuil_jours >= 0),
    -- relance_frequence_jours : délai minimal entre deux relances pour le même frais, pour ne
    -- pas spammer un même parent chaque jour tant que la dette n'est pas soldée.
    relance_frequence_jours INT NOT NULL DEFAULT 7 CHECK (relance_frequence_jours >= 1),
    communication_mode VARCHAR(20) NOT NULL DEFAULT 'demo' CHECK (communication_mode IN ('demo','production')),
    demo_email_daily_limit INTEGER NOT NULL DEFAULT 20 CHECK (demo_email_daily_limit >= 0),
    demo_whatsapp_daily_limit INTEGER NOT NULL DEFAULT 5 CHECK (demo_whatsapp_daily_limit >= 0),
    backup_retention_days INTEGER NOT NULL DEFAULT 30 CHECK (backup_retention_days >= 1),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- La ligne de paramètres initiale est fournie par database/seed.sql.

-- TABLE cycle
CREATE TABLE cycle (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(50) NOT NULL UNIQUE,
    ordre INT NOT NULL UNIQUE CHECK (ordre > 0)
);

-- TABLE niveau
CREATE TABLE niveau (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id INT NOT NULL,
    nom VARCHAR(50) NOT NULL,
    ordre INT NOT NULL CHECK (ordre > 0),
    CONSTRAINT uk_niveau_cycle_nom UNIQUE (cycle_id, nom),
    CONSTRAINT uk_niveau_cycle_ordre UNIQUE (cycle_id, ordre),
    CONSTRAINT fk_niveau_cycle FOREIGN KEY (cycle_id) REFERENCES cycle(id) ON DELETE CASCADE
);

-- TABLE bimestre
CREATE TABLE bimestre (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annee_scolaire_id INT NOT NULL,
    numero INT NOT NULL CHECK (numero IN (1, 2, 3, 4, 5)),
    libelle VARCHAR(50) NOT NULL,
    date_debut DATE NOT NULL,
    date_fin DATE NOT NULL,
    actif BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_bimestre_annee UNIQUE (annee_scolaire_id, numero),
    CONSTRAINT uk_bimestre_id_annee UNIQUE (id, annee_scolaire_id),
    CONSTRAINT chk_bimestre_dates CHECK (date_fin > date_debut),
    CONSTRAINT fk_bim_annee FOREIGN KEY (annee_scolaire_id) REFERENCES annee_scolaire(id) ON DELETE CASCADE
);

-- TABLE matiere
CREATE TABLE matiere (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL UNIQUE,
    code VARCHAR(20) UNIQUE,
    coefficient INT NOT NULL DEFAULT 1 CHECK (coefficient BETWEEN 1 AND 7),
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    couleur VARCHAR(20),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- TABLE classe
CREATE TABLE classe (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    niveau_id INT NOT NULL,
    filiere VARCHAR(100),
    salle VARCHAR(50) NOT NULL,
    titulaire_id INT,
    annee_scolaire_id INT NOT NULL,
    capacite INT CHECK (capacite IS NULL OR capacite > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_classe_annee UNIQUE (nom, annee_scolaire_id),
    CONSTRAINT fk_classe_titulaire FOREIGN KEY (titulaire_id) REFERENCES utilisateur(id) ON DELETE SET NULL,
    CONSTRAINT fk_classe_annee FOREIGN KEY (annee_scolaire_id) REFERENCES annee_scolaire(id) ON DELETE CASCADE
);

-- TABLE classe_matiere
CREATE TABLE classe_matiere (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classe_id INT NOT NULL,
    matiere_id INT NOT NULL,
    coefficient INT NOT NULL DEFAULT 1 CHECK (coefficient BETWEEN 1 AND 7),
    heures_semaine INT NOT NULL DEFAULT 2 CHECK (heures_semaine BETWEEN 2 AND 8),
    CONSTRAINT uk_classe_matiere UNIQUE (classe_id, matiere_id),
    CONSTRAINT fk_cm_classe FOREIGN KEY (classe_id) REFERENCES classe(id) ON DELETE CASCADE,
    CONSTRAINT fk_cm_matiere FOREIGN KEY (matiere_id) REFERENCES matiere(id) ON DELETE CASCADE
);

-- TABLE enseignant_matiere
CREATE TABLE enseignant_matiere (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enseignant_id INT NOT NULL,
    matiere_id INT NOT NULL,
    annee_scolaire_id INT NOT NULL,
    CONSTRAINT uk_ens_mat_annee UNIQUE (enseignant_id, matiere_id, annee_scolaire_id),
    CONSTRAINT fk_em_enseignant FOREIGN KEY (enseignant_id) REFERENCES utilisateur(id) ON DELETE CASCADE,
    CONSTRAINT fk_em_matiere FOREIGN KEY (matiere_id) REFERENCES matiere(id) ON DELETE CASCADE,
    CONSTRAINT fk_em_annee FOREIGN KEY (annee_scolaire_id) REFERENCES annee_scolaire(id) ON DELETE CASCADE
);

-- TABLE enseignant_matiere_classe
CREATE TABLE enseignant_matiere_classe (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enseignant_id INT NOT NULL,
    matiere_id INT NOT NULL,
    classe_id INT NOT NULL,
    annee_scolaire_id INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_emc UNIQUE (enseignant_id, matiere_id, classe_id, annee_scolaire_id),
    CONSTRAINT fk_emc_enseignant FOREIGN KEY (enseignant_id) REFERENCES utilisateur(id) ON DELETE CASCADE,
    CONSTRAINT fk_emc_matiere FOREIGN KEY (matiere_id) REFERENCES matiere(id) ON DELETE CASCADE,
    CONSTRAINT fk_emc_classe FOREIGN KEY (classe_id) REFERENCES classe(id) ON DELETE CASCADE,
    CONSTRAINT fk_emc_annee FOREIGN KEY (annee_scolaire_id) REFERENCES annee_scolaire(id) ON DELETE CASCADE,
    CONSTRAINT fk_emc_enseignant_matiere FOREIGN KEY (enseignant_id, matiere_id, annee_scolaire_id)
        REFERENCES enseignant_matiere(enseignant_id, matiere_id, annee_scolaire_id) ON DELETE RESTRICT,
    CONSTRAINT fk_emc_cm FOREIGN KEY (classe_id, matiere_id)
        REFERENCES classe_matiere(classe_id, matiere_id) ON DELETE CASCADE
);

-- TABLE eleve
CREATE TABLE eleve (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricule VARCHAR(50) UNIQUE NOT NULL,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100),
    date_naissance DATE,
    lieu_naissance VARCHAR(150),
    sexe VARCHAR(10) CHECK (sexe IS NULL OR sexe IN ('M', 'F')),
    adresse VARCHAR(255),
    telephone VARCHAR(30),
    email VARCHAR(150),
    photo_url TEXT,
    qr_code_data TEXT,
    numero_carte VARCHAR(50),
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- TABLE inscription
CREATE TABLE inscription (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eleve_id INT NOT NULL,
    classe_id INT NOT NULL,
    annee_scolaire_id INT NOT NULL,
    date_inscription DATE NOT NULL DEFAULT CURRENT_DATE,
    numero_classe INT CHECK (numero_classe IS NULL OR numero_classe > 0),
    statut VARCHAR(30) NOT NULL DEFAULT 'inscrit' CHECK (statut IN ('inscrit', 'en_cours', 'termine', 'abandonne', 'exclu')),
    observation TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_eleve_annee UNIQUE (eleve_id, annee_scolaire_id),
    CONSTRAINT uk_inscription_eleve_classe_annee UNIQUE (eleve_id, classe_id, annee_scolaire_id),
    CONSTRAINT fk_insc_eleve FOREIGN KEY (eleve_id) REFERENCES eleve(id) ON DELETE CASCADE,
    CONSTRAINT fk_insc_classe FOREIGN KEY (classe_id) REFERENCES classe(id) ON DELETE RESTRICT,
    CONSTRAINT fk_insc_annee FOREIGN KEY (annee_scolaire_id) REFERENCES annee_scolaire(id) ON DELETE RESTRICT
);

-- TABLE emploi_du_temps
-- TABLE salle : salles physiques avec QR code statique (porte) + géofence GPS.
-- rayon_metres définit le périmètre accepté autour de (latitude, longitude) pour valider un scan.
CREATE TABLE salle (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL UNIQUE,
    qr_code_data VARCHAR(64) NOT NULL UNIQUE,
    latitude DECIMAL(10,7),
    longitude DECIMAL(10,7),
    rayon_metres INT NOT NULL DEFAULT 100 CHECK (rayon_metres > 0),
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE emploi_du_temps (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classe_id INT NOT NULL,
    matiere_id INT NOT NULL,
    enseignant_id INT NOT NULL,
    annee_scolaire_id INT NOT NULL,
    jour VARCHAR(15) NOT NULL CHECK (jour IN ('Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi')),
    heure_debut TIME NOT NULL,
    heure_fin TIME NOT NULL,
    salle VARCHAR(50),
    salle_id INT,
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_heures_edt CHECK (heure_fin > heure_debut),
    CONSTRAINT fk_edt_classe FOREIGN KEY (classe_id) REFERENCES classe(id) ON DELETE CASCADE,
    CONSTRAINT fk_edt_matiere FOREIGN KEY (matiere_id) REFERENCES matiere(id) ON DELETE CASCADE,
    CONSTRAINT fk_edt_enseignant FOREIGN KEY (enseignant_id) REFERENCES utilisateur(id) ON DELETE RESTRICT,
    CONSTRAINT fk_edt_annee FOREIGN KEY (annee_scolaire_id) REFERENCES annee_scolaire(id) ON DELETE CASCADE,
    CONSTRAINT fk_edt_salle FOREIGN KEY (salle_id) REFERENCES salle(id) ON DELETE SET NULL,
    CONSTRAINT uk_edt_id_context UNIQUE (id, classe_id, matiere_id, enseignant_id, annee_scolaire_id),
    CONSTRAINT uk_edt_id_classe_ens_annee UNIQUE (id, classe_id, enseignant_id, annee_scolaire_id),
    -- Source de vérité : impossible d'inscrire un enseignant sur une matière/classe
    -- qui ne lui a pas été affectée pour cette année.
    CONSTRAINT fk_edt_enseignant_matiere_classe
        FOREIGN KEY (enseignant_id, matiere_id, classe_id, annee_scolaire_id)
        REFERENCES enseignant_matiere_classe(enseignant_id, matiere_id, classe_id, annee_scolaire_id)
        ON DELETE RESTRICT
);

-- TABLE pointage_enseignant : présence enseignant. Couvre 2 sources :
--   'manuel'  -> saisi par un agent/admin (comportement d'origine, heure_arrivee/heure_depart)
--   'scan_qr' -> auto-déclaré par l'enseignant (QR salle + GPS + fenêtre horaire), voir colonnes scan_*
CREATE TABLE pointage_enseignant (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enseignant_id INT NOT NULL,
    agent_id INT,
    emploi_du_temps_id INT NOT NULL,
    date_pointage DATE NOT NULL,
    heure_arrivee TIME,
    heure_depart TIME,
    statut VARCHAR(20) NOT NULL CHECK (statut IN ('present', 'absent', 'retard')),
    commentaire TEXT,

    -- Traçabilité / anti-doublon pour la synchronisation offline (uuid généré côté app mobile)
    uuid_local VARCHAR(64) UNIQUE,
    source VARCHAR(20) NOT NULL DEFAULT 'manuel' CHECK (source IN ('manuel', 'scan_qr')),
    salle_id INT,

    -- Scan d'entrée
    heure_scan_entree TIMESTAMPTZ,       -- horloge du TÉLÉPHONE au moment du scan (timestamp_local envoyé par l'app)
    heure_serveur_entree TIMESTAMPTZ,    -- horloge du SERVEUR à la réception de la requête (référence fiable)
    gps_lat_entree DECIMAL(10,7),
    gps_lng_entree DECIMAL(10,7),
    gps_precision_entree DECIMAL(6,1),
    gps_mock_entree BOOLEAN NOT NULL DEFAULT FALSE,

    -- Scan de sortie
    heure_scan_sortie TIMESTAMPTZ,       -- horloge du TÉLÉPHONE (timestamp_local)
    heure_serveur_sortie TIMESTAMPTZ,    -- horloge du SERVEUR à la réception
    gps_lat_sortie DECIMAL(10,7),
    gps_lng_sortie DECIMAL(10,7),
    gps_precision_sortie DECIMAL(6,1),
    gps_mock_sortie BOOLEAN NOT NULL DEFAULT FALSE,

    -- Preuve de vérification selfie (2e facteur) réalisée juste avant le scan
    selfie_verifie_a TIMESTAMPTZ,
    selfie_score DECIMAL(5,4),
    selfie_verifie_a_sortie TIMESTAMPTZ,
    selfie_score_sortie DECIMAL(5,4),

    -- Calculs dérivés (précis, en minutes)
    retard_minutes INT NOT NULL DEFAULT 0 CHECK (retard_minutes >= 0),
    depart_anticipe_minutes INT NOT NULL DEFAULT 0 CHECK (depart_anticipe_minutes >= 0),
    duree_reelle_minutes INT CHECK (duree_reelle_minutes IS NULL OR duree_reelle_minutes >= 0),
    duree_payee_minutes INT CHECK (duree_payee_minutes IS NULL OR duree_payee_minutes >= 0),

    -- Cas "entrée sans sortie" (ou tout autre cas ambigu) : nécessite arbitrage admin
    statut_validation VARCHAR(25) NOT NULL DEFAULT 'auto'
        CHECK (statut_validation IN ('auto', 'en_attente_validation', 'valide_admin', 'rejete')),
    raison_refus VARCHAR(50),
    valide_par_id INT,
    valide_par_agent_id INT,
    date_validation TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_pointage_ens UNIQUE (enseignant_id, emploi_du_temps_id, date_pointage),
    CONSTRAINT fk_pe_enseignant FOREIGN KEY (enseignant_id) REFERENCES utilisateur(id) ON DELETE CASCADE,
    -- SET NULL (et non CASCADE) : cohérent avec toutes les autres FK "agent_id"
    -- de la base (paiement, notification, actualite, depense, discipline, ...).
    -- Supprimer un agent ne doit jamais effacer l'historique de pointage des enseignants.
    CONSTRAINT fk_pe_agent FOREIGN KEY (agent_id) REFERENCES agent(id) ON DELETE SET NULL,
    -- RESTRICT (et non SET NULL) : emploi_du_temps_id est NOT NULL ci-dessus, donc SET NULL
    -- provoquait une erreur PostgreSQL au premier DELETE d'un créneau EDT déjà pointé.
    CONSTRAINT fk_pe_edt FOREIGN KEY (emploi_du_temps_id) REFERENCES emploi_du_temps(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pe_salle FOREIGN KEY (salle_id) REFERENCES salle(id) ON DELETE SET NULL,
    CONSTRAINT fk_pe_valide_par FOREIGN KEY (valide_par_id) REFERENCES utilisateur(id) ON DELETE SET NULL,
    CONSTRAINT fk_pe_valide_par_agent FOREIGN KEY (valide_par_agent_id) REFERENCES agent(id) ON DELETE SET NULL
);

CREATE INDEX idx_pointage_enseignant_date ON pointage_enseignant(enseignant_id, date_pointage);

-- TABLE pointage_eleve
CREATE TABLE pointage_eleve (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eleve_id INT NOT NULL,
    classe_id INT NOT NULL,
    annee_scolaire_id INT NOT NULL,
    agent_id INT,
    enseignant_id INT NOT NULL,
    emploi_du_temps_id INT NOT NULL,
    date_pointage DATE NOT NULL,
    heure_arrivee TIME,
    heure_depart TIME,
    statut VARCHAR(20) NOT NULL CHECK (statut IN ('present', 'absent', 'retard')),
    commentaire TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_pointage_elv UNIQUE (eleve_id, emploi_du_temps_id, date_pointage),
    CONSTRAINT fk_pel_eleve FOREIGN KEY (eleve_id) REFERENCES eleve(id) ON DELETE CASCADE,
    CONSTRAINT fk_pel_classe FOREIGN KEY (classe_id) REFERENCES classe(id) ON DELETE CASCADE,
    CONSTRAINT fk_pel_annee FOREIGN KEY (annee_scolaire_id) REFERENCES annee_scolaire(id) ON DELETE CASCADE,
    CONSTRAINT fk_pel_agent FOREIGN KEY (agent_id) REFERENCES agent(id) ON DELETE SET NULL,
    CONSTRAINT fk_pel_edt_context FOREIGN KEY (emploi_du_temps_id, classe_id, enseignant_id, annee_scolaire_id)
        REFERENCES emploi_du_temps(id, classe_id, enseignant_id, annee_scolaire_id) ON DELETE RESTRICT,
    CONSTRAINT fk_pel_inscription FOREIGN KEY (eleve_id, classe_id, annee_scolaire_id)
        REFERENCES inscription(eleve_id, classe_id, annee_scolaire_id) ON DELETE RESTRICT
);

-- TABLE note
CREATE TABLE note (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eleve_id INT NOT NULL,
    classe_id INT NOT NULL,
    matiere_id INT NOT NULL,
    enseignant_id INT NOT NULL,
    annee_scolaire_id INT NOT NULL,
    bimestre_id INT NOT NULL,
    note_valeur DECIMAL(5,2) NOT NULL CHECK (note_valeur BETWEEN 0 AND 20),
    type_evaluation VARCHAR(50),
    coefficient_evaluation DECIMAL(4,2) NOT NULL DEFAULT 1 CHECK (coefficient_evaluation > 0),
    commentaire TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_note_eleve FOREIGN KEY (eleve_id) REFERENCES eleve(id) ON DELETE CASCADE,
    CONSTRAINT fk_note_assignment FOREIGN KEY (enseignant_id, matiere_id, classe_id, annee_scolaire_id)
        REFERENCES enseignant_matiere_classe(enseignant_id, matiere_id, classe_id, annee_scolaire_id) ON DELETE RESTRICT,
    CONSTRAINT fk_note_inscription FOREIGN KEY (eleve_id, classe_id, annee_scolaire_id)
        REFERENCES inscription(eleve_id, classe_id, annee_scolaire_id) ON DELETE RESTRICT,
    CONSTRAINT fk_note_bimestre FOREIGN KEY (bimestre_id) REFERENCES bimestre(id) ON DELETE RESTRICT
);

-- TABLE bulletin
CREATE TABLE bulletin (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eleve_id INT NOT NULL,
    classe_id INT NOT NULL,
    annee_scolaire_id INT NOT NULL,
    bimestre_id INT NOT NULL,
    moyenne_generale DECIMAL(5,2) CHECK (moyenne_generale IS NULL OR moyenne_generale BETWEEN 0 AND 20),
    total_points DECIMAL(8,2),
    total_coefficients DECIMAL(8,2),
    rang INT CHECK (rang IS NULL OR rang > 0),
    effectif_classe INT CHECK (effectif_classe IS NULL OR effectif_classe > 0),
    decision VARCHAR(50),
    appreciation_generale TEXT,
    absent_total INT NOT NULL DEFAULT 0 CHECK (absent_total >= 0),
    retard_total INT NOT NULL DEFAULT 0 CHECK (retard_total >= 0),
    date_generation TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_bulletin_bimestre UNIQUE (eleve_id, annee_scolaire_id, bimestre_id),
    CONSTRAINT fk_bul_eleve FOREIGN KEY (eleve_id) REFERENCES eleve(id) ON DELETE CASCADE,
    CONSTRAINT fk_bul_classe FOREIGN KEY (classe_id) REFERENCES classe(id) ON DELETE RESTRICT,
    CONSTRAINT fk_bul_annee FOREIGN KEY (annee_scolaire_id) REFERENCES annee_scolaire(id) ON DELETE RESTRICT,
    CONSTRAINT fk_bul_bimestre FOREIGN KEY (bimestre_id) REFERENCES bimestre(id) ON DELETE RESTRICT,
    CONSTRAINT fk_bul_inscription FOREIGN KEY (eleve_id, classe_id, annee_scolaire_id) REFERENCES inscription(eleve_id, classe_id, annee_scolaire_id) ON DELETE RESTRICT
);

-- TABLE bulletin_matiere
CREATE TABLE bulletin_matiere (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulletin_id INT NOT NULL,
    matiere_id INT NOT NULL,
    moyenne DECIMAL(5,2) CHECK (moyenne IS NULL OR moyenne BETWEEN 0 AND 20),
    coefficient INT NOT NULL CHECK (coefficient BETWEEN 1 AND 7),
    total_points DECIMAL(8,2),
    rang_matiere INT CHECK (rang_matiere IS NULL OR rang_matiere > 0),
    appreciation TEXT,
    CONSTRAINT uk_bulletin_matiere UNIQUE (bulletin_id, matiere_id),
    CONSTRAINT fk_bm_bulletin FOREIGN KEY (bulletin_id) REFERENCES bulletin(id) ON DELETE CASCADE,
    CONSTRAINT fk_bm_matiere FOREIGN KEY (matiere_id) REFERENCES matiere(id) ON DELETE RESTRICT
);

-- TABLE devoir
CREATE TABLE devoir (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classe_id INT NOT NULL,
    matiere_id INT NOT NULL,
    enseignant_id INT NOT NULL,
    annee_scolaire_id INT NOT NULL,
    titre VARCHAR(200) NOT NULL,
    consignes TEXT,
    date_assignation DATE NOT NULL,
    date_limite DATE,
    fichier_url VARCHAR(500),
    envoye BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_date_limite CHECK (date_limite IS NULL OR date_limite >= date_assignation),
    CONSTRAINT fk_dev_classe FOREIGN KEY (classe_id) REFERENCES classe(id) ON DELETE CASCADE,
    CONSTRAINT fk_dev_matiere FOREIGN KEY (matiere_id) REFERENCES matiere(id) ON DELETE CASCADE,
    -- RESTRICT (et non SET NULL) : enseignant_id est NOT NULL ci-dessus, donc SET NULL
    -- provoquait une erreur PostgreSQL au premier DELETE d'un enseignant ayant des devoirs.
    CONSTRAINT fk_dev_enseignant FOREIGN KEY (enseignant_id) REFERENCES utilisateur(id) ON DELETE RESTRICT,
    CONSTRAINT fk_dev_annee FOREIGN KEY (annee_scolaire_id) REFERENCES annee_scolaire(id) ON DELETE CASCADE
);

-- TABLE absence_enseignant
-- auteur_utilisateur_id / auteur_agent_id : qui a déclaré/saisi l'absence (admin = utilisateur,
-- surveillant/secretaire = agent) — jusqu'ici cette table ne gardait aucune trace de l'auteur,
-- rendant le travail quotidien du secrétariat sur ce module invisible partout (Historique, Audit).
-- Même convention que discipline.auteur_utilisateur_id / auteur_agent_id.
CREATE TABLE absence_enseignant (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enseignant_id INT NOT NULL,
    emploi_du_temps_id INT,
    date_absence DATE NOT NULL,
    motif TEXT,
    justifiee BOOLEAN NOT NULL DEFAULT FALSE,
    auteur_utilisateur_id INT,
    auteur_agent_id INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_abs_ens UNIQUE (enseignant_id, emploi_du_temps_id, date_absence),
    CONSTRAINT fk_absens_enseignant FOREIGN KEY (enseignant_id) REFERENCES utilisateur(id) ON DELETE CASCADE,
    CONSTRAINT fk_absens_edt FOREIGN KEY (emploi_du_temps_id) REFERENCES emploi_du_temps(id) ON DELETE SET NULL,
    CONSTRAINT fk_absens_utilisateur FOREIGN KEY (auteur_utilisateur_id) REFERENCES utilisateur(id) ON DELETE SET NULL,
    CONSTRAINT fk_absens_agent FOREIGN KEY (auteur_agent_id) REFERENCES agent(id) ON DELETE SET NULL
);

-- TABLE absence_eleve (mêmes colonnes auteur_* que ci-dessus, même raison)
CREATE TABLE absence_eleve (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eleve_id INT NOT NULL,
    emploi_du_temps_id INT,
    date_absence DATE NOT NULL,
    motif TEXT,
    justifiee BOOLEAN NOT NULL DEFAULT FALSE,
    document_justificatif VARCHAR(500),
    auteur_utilisateur_id INT,
    auteur_agent_id INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_abs_elv UNIQUE (eleve_id, emploi_du_temps_id, date_absence),
    CONSTRAINT fk_abs_eleve FOREIGN KEY (eleve_id) REFERENCES eleve(id) ON DELETE CASCADE,
    CONSTRAINT fk_abs_edt FOREIGN KEY (emploi_du_temps_id) REFERENCES emploi_du_temps(id) ON DELETE SET NULL,
    CONSTRAINT fk_abs_utilisateur FOREIGN KEY (auteur_utilisateur_id) REFERENCES utilisateur(id) ON DELETE SET NULL,
    CONSTRAINT fk_abs_agent FOREIGN KEY (auteur_agent_id) REFERENCES agent(id) ON DELETE SET NULL
);

-- TABLE salaire_enseignant
CREATE TABLE salaire_enseignant (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enseignant_id INT NOT NULL,
    type_salaire VARCHAR(30) NOT NULL CHECK (type_salaire IN ('mensuel', 'horaire')),
    montant DECIMAL(12,2) NOT NULL CHECK (montant >= 0),
    date_debut DATE NOT NULL,
    date_fin DATE,
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_salaire_dates CHECK (date_fin IS NULL OR date_fin >= date_debut),
    CONSTRAINT fk_sal_enseignant FOREIGN KEY (enseignant_id) REFERENCES utilisateur(id) ON DELETE CASCADE
);

-- TABLE paie
CREATE TABLE paie (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enseignant_id INT NOT NULL,
    salaire_id INT,
    mois INT NOT NULL CHECK (mois BETWEEN 1 AND 12),
    annee INT NOT NULL CHECK (annee >= 2000),
    heures_normales DECIMAL(8,2) NOT NULL DEFAULT 0 CHECK (heures_normales >= 0),
    heures_supplementaires DECIMAL(8,2) NOT NULL DEFAULT 0 CHECK (heures_supplementaires >= 0),
    salaire_base DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (salaire_base >= 0),
    prime DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (prime >= 0),
    retenue DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (retenue >= 0),
    salaire_brut DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (salaire_brut >= 0),
    salaire_net DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (salaire_net >= 0),
    statut VARCHAR(30) NOT NULL DEFAULT 'prepare' CHECK (statut IN ('prepare', 'valide', 'paye', 'annule')),
    date_paiement DATE,
    mode_paiement VARCHAR(30) CHECK (mode_paiement IS NULL OR mode_paiement IN ('especes', 'virement', 'cheque', 'mobile_money', 'carte', 'autre')),
    reference_paiement VARCHAR(100),
    commentaire TEXT,
    -- Pilotage professionnel (ex-migration V6) : snapshot de la grille tarifaire au moment
    -- de préparer la paie, pour qu'une modification ultérieure du tarif ne change jamais
    -- un bulletin déjà préparé, plus le détail heures planifiées/effectuées/absence.
    tarif_horaire_snapshot DECIMAL(12,2),
    coefficient_supplementaire DECIMAL(6,3) NOT NULL DEFAULT 1 CHECK (coefficient_supplementaire > 0),
    heures_planifiees DECIMAL(8,2) NOT NULL DEFAULT 0 CHECK (heures_planifiees >= 0),
    heures_effectuees DECIMAL(8,2) NOT NULL DEFAULT 0 CHECK (heures_effectuees >= 0),
    heures_absence DECIMAL(8,2) NOT NULL DEFAULT 0 CHECK (heures_absence >= 0),
    montant_heures_normales DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (montant_heures_normales >= 0),
    montant_heures_supplementaires DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (montant_heures_supplementaires >= 0),
    reference_paie VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_paie_enseignant FOREIGN KEY (enseignant_id) REFERENCES utilisateur(id) ON DELETE RESTRICT,
    CONSTRAINT fk_paie_salaire FOREIGN KEY (salaire_id) REFERENCES salaire_enseignant(id) ON DELETE SET NULL
);

-- Un seul bulletin ACTIF (non annulé) par enseignant/mois/année : index unique partiel
-- plutôt qu'une contrainte UNIQUE classique, pour qu'annuler un bulletin libère bien la
-- période et permette d'en générer un nouveau corrigé (sinon l'admin reste bloqué).
CREATE UNIQUE INDEX uk_paie_mois_annee_actif ON paie (enseignant_id, mois, annee) WHERE statut <> 'annule';

CREATE UNIQUE INDEX uk_paie_reference ON paie(reference_paie) WHERE reference_paie IS NOT NULL;
CREATE INDEX idx_paie_periode_enseignant ON paie(annee, mois, enseignant_id);

-- TABLE controle_paie (ex-migration V6) : historique métier du contrôle de paie,
-- pour que les validations restent traçables.
CREATE TABLE controle_paie (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enseignant_id INT NOT NULL,
    mois INT NOT NULL CHECK (mois BETWEEN 1 AND 12),
    annee INT NOT NULL CHECK (annee >= 2000),
    heures_planifiees DECIMAL(8,2) NOT NULL DEFAULT 0 CHECK (heures_planifiees >= 0),
    heures_effectuees DECIMAL(8,2) NOT NULL DEFAULT 0 CHECK (heures_effectuees >= 0),
    heures_absence DECIMAL(8,2) NOT NULL DEFAULT 0 CHECK (heures_absence >= 0),
    heures_en_attente DECIMAL(8,2) NOT NULL DEFAULT 0 CHECK (heures_en_attente >= 0),
    ecart_heures DECIMAL(8,2) NOT NULL DEFAULT 0,
    tarif_horaire DECIMAL(12,2),
    montant_estime DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (montant_estime >= 0),
    statut VARCHAR(25) NOT NULL DEFAULT 'a_verifier' CHECK (statut IN ('ok','a_verifier','incomplet')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_controle_paie UNIQUE (enseignant_id, mois, annee),
    CONSTRAINT fk_controle_paie_enseignant FOREIGN KEY (enseignant_id) REFERENCES utilisateur(id) ON DELETE CASCADE
);

CREATE INDEX idx_controle_paie_periode ON controle_paie(annee, mois, statut);

-- Intégrité (ex-migration V6) : une paie payée ne peut pas être recréditée silencieusement.
CREATE OR REPLACE FUNCTION fn_proteger_paie_payee()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.statut = 'paye' AND (
    NEW.enseignant_id IS DISTINCT FROM OLD.enseignant_id OR
    NEW.mois IS DISTINCT FROM OLD.mois OR
    NEW.annee IS DISTINCT FROM OLD.annee OR
    NEW.salaire_net IS DISTINCT FROM OLD.salaire_net OR
    NEW.heures_normales IS DISTINCT FROM OLD.heures_normales OR
    NEW.heures_supplementaires IS DISTINCT FROM OLD.heures_supplementaires
  ) THEN
    RAISE EXCEPTION 'Bulletin de paie déjà payé : modification financière interdite. Annulez/régularisez par une pièce comptable explicite.';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_proteger_paie_payee
BEFORE UPDATE ON paie FOR EACH ROW EXECUTE FUNCTION fn_proteger_paie_payee();

-- TABLE tarif_frais
-- Grille tarifaire de référence : montant attendu par niveau, par type de frais, pour une
-- année scolaire donnée (ex: Écolage 6ème 2026-2027 = 25000 Ar/mois). Sert de source pour
-- la génération automatique des frais_scolaire (voir routes/finance.js -> POST
-- /finance/tarifs/generer) : l'admin/économe modifie cette grille une seule fois par niveau,
-- et le montant s'applique ensuite automatiquement à tous les élèves de ce niveau.
-- recurrent_mensuel = TRUE  -> frais dû chaque mois (écolage) : la génération demande un mois.
-- recurrent_mensuel = FALSE -> frais dû une seule fois dans l'année (droit, examen national...).
CREATE TABLE tarif_frais (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    niveau_id INT NOT NULL,
    annee_scolaire_id INT NOT NULL,
    type_frais VARCHAR(50) NOT NULL,
    libelle VARCHAR(200),
    montant DECIMAL(12,2) NOT NULL CHECK (montant >= 0),
    recurrent_mensuel BOOLEAN NOT NULL DEFAULT FALSE,
    -- jour_echeance : jour du mois (1-28) où ce tarif précis est dû (ex: écolage niveau 6ème
    -- payable avant le 5 de chaque mois). NULL -> POST /finance/tarifs/generer retombe sur
    -- parametre_ecole.jour_echeance_defaut. Permet une règle par niveau/type sans avoir à la
    -- ressaisir manuellement à chaque génération mensuelle (voir routes/finance.js).
    jour_echeance INT CHECK (jour_echeance IS NULL OR jour_echeance BETWEEN 1 AND 28),
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tarif_niveau_type_annee UNIQUE (niveau_id, type_frais, annee_scolaire_id),
    CONSTRAINT fk_tarif_niveau FOREIGN KEY (niveau_id) REFERENCES niveau(id) ON DELETE CASCADE,
    CONSTRAINT fk_tarif_annee FOREIGN KEY (annee_scolaire_id) REFERENCES annee_scolaire(id) ON DELETE CASCADE
);

-- TABLE frais_scolaire
CREATE TABLE frais_scolaire (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eleve_id INT NOT NULL,
    annee_scolaire_id INT NOT NULL,
    type_frais VARCHAR(50) NOT NULL,
    libelle VARCHAR(200),
    montant_total DECIMAL(12,2) NOT NULL CHECK (montant_total >= 0),
    -- mois : 1-12, rempli uniquement pour un frais récurrent mensuel (ex: écolage par mois).
    -- NULL pour un frais unique (inscription, examen...). Permet le suivi "écolage de tel mois".
    mois INT CHECK (mois IS NULL OR mois BETWEEN 1 AND 12),
    date_echeance DATE,
    statut VARCHAR(30) NOT NULL DEFAULT 'impaye' CHECK (statut IN ('impaye', 'partiel', 'paye', 'annule')),
    -- tarif_id : renseigné uniquement quand ce frais a été créé automatiquement à partir de
    -- la grille tarif_frais (voir POST /finance/tarifs/generer). NULL pour un frais saisi à la
    -- main (cas particulier élève par élève, comme avant). Sert à éviter les doublons lors
    -- d'une nouvelle génération et à distinguer "auto" de "manuel" dans l'historique.
    tarif_id INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_frais_eleve FOREIGN KEY (eleve_id) REFERENCES eleve(id) ON DELETE CASCADE,
    CONSTRAINT fk_frais_annee FOREIGN KEY (annee_scolaire_id) REFERENCES annee_scolaire(id) ON DELETE CASCADE,
    CONSTRAINT fk_frais_tarif FOREIGN KEY (tarif_id) REFERENCES tarif_frais(id) ON DELETE SET NULL
);

-- TABLE paiement
CREATE TABLE paiement (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    frais_id INT NOT NULL,
    eleve_id INT NOT NULL,
    montant DECIMAL(12,2) NOT NULL CHECK (montant > 0),
    mode_paiement VARCHAR(30) NOT NULL CHECK (mode_paiement IN ('especes', 'virement', 'cheque', 'mobile_money', 'carte', 'autre')),
    reference_paiement VARCHAR(100),
    date_paiement DATE NOT NULL DEFAULT CURRENT_DATE,
    recu_numero VARCHAR(100) UNIQUE,
    utilisateur_id INT,
    agent_id INT,
    commentaire TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_paiement_frais FOREIGN KEY (frais_id) REFERENCES frais_scolaire(id) ON DELETE CASCADE,
    CONSTRAINT fk_paiement_eleve FOREIGN KEY (eleve_id) REFERENCES eleve(id) ON DELETE CASCADE,
    CONSTRAINT fk_paiement_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur(id) ON DELETE SET NULL,
    CONSTRAINT fk_paiement_agent FOREIGN KEY (agent_id) REFERENCES agent(id) ON DELETE SET NULL
);

-- TABLE relance_impaye
-- Historique des relances (email/SMS) envoyées aux parents pour un frais_scolaire en retard
-- (impaye/partiel dont la date_echeance est dépassée). Générée automatiquement par le cron
-- quotidien (services/relanceService.js, voir jobs/cron.js) ou déclenchée manuellement par
-- l'économe (POST /finance/relances/generer). Distincte de envoi_rapport (bulletins/actualités,
-- portée large) : ici chaque ligne est rattachée précisément à UN frais + UN élève, ce qui
-- permet de savoir "ce frais a-t-il déjà été relancé, et quand ?" avant d'en renvoyer une autre
-- (respect de relance_frequence_jours, voir parametre_ecole).
CREATE TABLE relance_impaye (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    frais_id INT NOT NULL,
    eleve_id INT NOT NULL,
    jours_retard INT NOT NULL CHECK (jours_retard >= 0),
    montant_du DECIMAL(12,2) NOT NULL CHECK (montant_du >= 0),
    canal VARCHAR(20) NOT NULL CHECK (canal IN ('email', 'whatsapp', 'sms', 'les_deux')),
    email_statut VARCHAR(20) CHECK (email_statut IS NULL OR email_statut IN ('envoye', 'echec', 'non_applicable')),
    sms_statut VARCHAR(20) CHECK (sms_statut IS NULL OR sms_statut IN ('envoye', 'echec', 'non_applicable')),
    whatsapp_statut VARCHAR(20) CHECK (whatsapp_statut IS NULL OR whatsapp_statut IN ('envoye', 'echec', 'non_applicable')),
    -- manuel = TRUE quand un membre du staff a cliqué "Relancer maintenant" (une relance
    -- ponctuelle ignore relance_frequence_jours) ; FALSE pour une relance issue du cron.
    manuel BOOLEAN NOT NULL DEFAULT FALSE,
    utilisateur_id INT,
    agent_id INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_relance_frais FOREIGN KEY (frais_id) REFERENCES frais_scolaire(id) ON DELETE CASCADE,
    CONSTRAINT fk_relance_eleve FOREIGN KEY (eleve_id) REFERENCES eleve(id) ON DELETE CASCADE,
    CONSTRAINT fk_relance_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur(id) ON DELETE SET NULL,
    CONSTRAINT fk_relance_agent FOREIGN KEY (agent_id) REFERENCES agent(id) ON DELETE SET NULL
);
CREATE INDEX idx_relance_frais ON relance_impaye(frais_id);
CREATE INDEX idx_relance_eleve ON relance_impaye(eleve_id);

-- TABLE document_eleve
CREATE TABLE document_eleve (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eleve_id INT NOT NULL,
    type_document VARCHAR(50) NOT NULL,
    nom_fichier VARCHAR(255) NOT NULL,
    fichier_url VARCHAR(500) NOT NULL,
    description TEXT,
    date_document DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_doc_eleve FOREIGN KEY (eleve_id) REFERENCES eleve(id) ON DELETE CASCADE
);

-- TABLE certificat_scolarite : journal des attestations/certificats officiels délivrés à un élève
-- (accueil/secrétariat). Immuable une fois émis (pas de PUT/DELETE, même logique que "paiement" :
-- un document déjà remis à la famille ne se corrige pas, on en réémet un nouveau si besoin) —
-- ce qui en garde une trace fiable, numérotée, pour l'audit.
CREATE TABLE certificat_scolarite (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(50) UNIQUE NOT NULL,
    eleve_id INT NOT NULL,
    annee_scolaire_id INT NOT NULL,
    classe_id INT NOT NULL,
    type_certificat VARCHAR(30) NOT NULL DEFAULT 'scolarite'
        CHECK (type_certificat IN ('scolarite', 'frequentation', 'radiation')),
    motif VARCHAR(255),
    date_emission DATE NOT NULL DEFAULT CURRENT_DATE,
    utilisateur_id INT,
    agent_id INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cert_eleve FOREIGN KEY (eleve_id) REFERENCES eleve(id) ON DELETE CASCADE,
    CONSTRAINT fk_cert_annee FOREIGN KEY (annee_scolaire_id) REFERENCES annee_scolaire(id) ON DELETE RESTRICT,
    CONSTRAINT fk_cert_classe FOREIGN KEY (classe_id) REFERENCES classe(id) ON DELETE RESTRICT,
    CONSTRAINT fk_cert_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur(id) ON DELETE SET NULL,
    CONSTRAINT fk_cert_agent FOREIGN KEY (agent_id) REFERENCES agent(id) ON DELETE SET NULL
);
CREATE INDEX idx_certificat_eleve ON certificat_scolarite(eleve_id);

-- TABLE notification
CREATE TABLE notification (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eleve_id INT,
    auteur_admin_id INT,
    agent_id INT,
    titre VARCHAR(200),
    message TEXT NOT NULL,
    type_notification VARCHAR(50),
    lu BOOLEAN NOT NULL DEFAULT FALSE,
    date_lecture TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notif_eleve FOREIGN KEY (eleve_id) REFERENCES eleve(id) ON DELETE CASCADE,
    CONSTRAINT fk_notif_admin FOREIGN KEY (auteur_admin_id) REFERENCES utilisateur(id) ON DELETE SET NULL,
    CONSTRAINT fk_notif_agent FOREIGN KEY (agent_id) REFERENCES agent(id) ON DELETE SET NULL
);

-- TABLE envoi_rapport
CREATE TABLE envoi_rapport (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auteur_id INT,
    agent_id INT,
    scope_type VARCHAR(20) NOT NULL CHECK (scope_type IN ('tous', 'niveau', 'classe', 'eleve', 'selection')),
    scope_valeur VARCHAR(200),
    contenu VARCHAR(300) NOT NULL,
    canal VARCHAR(20) NOT NULL CHECK (canal IN ('email', 'whatsapp', 'les_deux')),
    bimestre_id INT,
    nb_destinataires INT NOT NULL DEFAULT 0,
    nb_envoyes_email INT NOT NULL DEFAULT 0,
    nb_envoyes_whatsapp INT NOT NULL DEFAULT 0,
    nb_echecs INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_envoi_auteur FOREIGN KEY (auteur_id) REFERENCES utilisateur(id) ON DELETE SET NULL,
    CONSTRAINT fk_envoi_agent FOREIGN KEY (agent_id) REFERENCES agent(id) ON DELETE SET NULL,
    CONSTRAINT fk_envoi_bimestre FOREIGN KEY (bimestre_id) REFERENCES bimestre(id) ON DELETE SET NULL
);

-- TABLE envoi_rapport_detail
CREATE TABLE envoi_rapport_detail (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    envoi_rapport_id INT NOT NULL,
    eleve_id INT,
    email_statut VARCHAR(20) CHECK (email_statut IS NULL OR email_statut IN ('envoye', 'echec', 'non_applicable')),
    whatsapp_statut VARCHAR(20) CHECK (whatsapp_statut IS NULL OR whatsapp_statut IN ('envoye', 'echec', 'non_applicable', 'non_configure')),
    erreur TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_envoidetail_envoi FOREIGN KEY (envoi_rapport_id) REFERENCES envoi_rapport(id) ON DELETE CASCADE,
    CONSTRAINT fk_envoidetail_eleve FOREIGN KEY (eleve_id) REFERENCES eleve(id) ON DELETE SET NULL
);

-- TABLE actualite
CREATE TABLE actualite (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre VARCHAR(200) NOT NULL,
    contenu TEXT NOT NULL,
    image_url VARCHAR(500),
    auteur_id INT,
    agent_id INT,
    publie BOOLEAN NOT NULL DEFAULT FALSE,
    date_publication TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_actu_auteur FOREIGN KEY (auteur_id) REFERENCES utilisateur(id) ON DELETE SET NULL,
    CONSTRAINT fk_actu_agent FOREIGN KEY (agent_id) REFERENCES agent(id) ON DELETE SET NULL
);

-- TABLE visiteur : registre d'accueil séparé du rôle surveillant.
CREATE TABLE visiteur (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100),
    telephone VARCHAR(30),
    motif VARCHAR(200) NOT NULL,
    personne_visitee VARCHAR(200),
    heure_entree TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    heure_sortie TIMESTAMPTZ,
    statut VARCHAR(20) NOT NULL DEFAULT 'present' CHECK (statut IN ('present','sorti','annule')),
    badge VARCHAR(50),
    observation TEXT,
    utilisateur_id INT REFERENCES utilisateur(id) ON DELETE SET NULL,
    agent_id INT REFERENCES agent(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_visiteur_sortie CHECK (heure_sortie IS NULL OR heure_sortie >= heure_entree)
);
CREATE INDEX idx_visiteur_entree ON visiteur(heure_entree DESC);
CREATE INDEX idx_visiteur_statut ON visiteur(statut);

-- TABLE parent
CREATE TABLE parent (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100),
    telephone VARCHAR(30) NOT NULL,
    telephone_2 VARCHAR(30),
    email VARCHAR(150),
    adresse VARCHAR(255),
    profession VARCHAR(150),
    piece_identite VARCHAR(50),
    photo_url TEXT,
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- TABLE eleve_parent
CREATE TABLE eleve_parent (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eleve_id INT NOT NULL,
    parent_id INT NOT NULL,
    lien_parente VARCHAR(30) NOT NULL CHECK (lien_parente IN ('pere', 'mere', 'tuteur', 'autre')),
    responsable_principal BOOLEAN NOT NULL DEFAULT FALSE,
    autorise_retrait BOOLEAN NOT NULL DEFAULT TRUE,
    recoit_notifications BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_eleve_parent UNIQUE (eleve_id, parent_id),
    CONSTRAINT fk_ep_eleve FOREIGN KEY (eleve_id) REFERENCES eleve(id) ON DELETE CASCADE,
    CONSTRAINT fk_ep_parent FOREIGN KEY (parent_id) REFERENCES parent(id) ON DELETE CASCADE
);

-- TABLE examen
CREATE TABLE examen (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annee_scolaire_id INT NOT NULL,
    classe_id INT NOT NULL,
    nom VARCHAR(150) NOT NULL,
    type_examen VARCHAR(30) NOT NULL CHECK (type_examen IN ('devoir', 'controle', 'examen', 'composition', 'examen_final')),
    bimestre_id INT NOT NULL,
    date_debut DATE NOT NULL,
    date_fin DATE NOT NULL,
    statut VARCHAR(20) NOT NULL DEFAULT 'planifie' CHECK (statut IN ('planifie', 'en_cours', 'termine', 'annule')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_examen_dates CHECK (date_fin >= date_debut),
    CONSTRAINT fk_exam_annee FOREIGN KEY (annee_scolaire_id) REFERENCES annee_scolaire(id) ON DELETE CASCADE,
    CONSTRAINT fk_exam_classe FOREIGN KEY (classe_id) REFERENCES classe(id) ON DELETE CASCADE,
    CONSTRAINT fk_exam_bimestre FOREIGN KEY (bimestre_id, annee_scolaire_id) REFERENCES bimestre(id, annee_scolaire_id) ON DELETE RESTRICT
);

-- TABLE examen_matiere
CREATE TABLE examen_matiere (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    examen_id INT NOT NULL,
    matiere_id INT NOT NULL,
    enseignant_id INT NOT NULL,
    date_examen DATE NOT NULL,
    heure_debut TIME,
    heure_fin TIME,
    coefficient INT NOT NULL DEFAULT 1 CHECK (coefficient BETWEEN 1 AND 7),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_examen_matiere UNIQUE (examen_id, matiere_id),
    CONSTRAINT chk_examen_matiere_heures CHECK (heure_debut IS NULL OR heure_fin IS NULL OR heure_fin > heure_debut),
    CONSTRAINT fk_exm_examen FOREIGN KEY (examen_id) REFERENCES examen(id) ON DELETE CASCADE,
    CONSTRAINT fk_exm_matiere FOREIGN KEY (matiere_id) REFERENCES matiere(id) ON DELETE CASCADE,
    CONSTRAINT fk_exm_enseignant FOREIGN KEY (enseignant_id) REFERENCES utilisateur(id) ON DELETE RESTRICT
);

-- TABLE resultat_examen
CREATE TABLE resultat_examen (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    examen_matiere_id INT NOT NULL,
    eleve_id INT NOT NULL,
    note DECIMAL(5,2) CHECK (note IS NULL OR note BETWEEN 0 AND 20),
    absence BOOLEAN NOT NULL DEFAULT FALSE,
    observation TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_resultat_examen UNIQUE (examen_matiere_id, eleve_id),
    CONSTRAINT chk_resultat_absence CHECK (absence = FALSE OR note IS NULL),
    CONSTRAINT fk_re_examen_matiere FOREIGN KEY (examen_matiere_id) REFERENCES examen_matiere(id) ON DELETE CASCADE,
    CONSTRAINT fk_re_eleve FOREIGN KEY (eleve_id) REFERENCES eleve(id) ON DELETE CASCADE
);

-- TABLE discipline
CREATE TABLE discipline (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eleve_id INT NOT NULL,
    date_incident DATE NOT NULL,
    type_incident VARCHAR(50) NOT NULL CHECK (type_incident IN ('absence_non_justifiee', 'retard_repete', 'violence', 'triche', 'comportement', 'autre')),
    description TEXT,
    sanction VARCHAR(200),
    gravite VARCHAR(20) NOT NULL DEFAULT 'faible' CHECK (gravite IN ('faible', 'moyenne', 'grave', 'tres_grave')),
    auteur_utilisateur_id INT,
    auteur_agent_id INT,
    parent_informe BOOLEAN NOT NULL DEFAULT FALSE,
    date_information_parent TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_disc_eleve FOREIGN KEY (eleve_id) REFERENCES eleve(id) ON DELETE CASCADE,
    CONSTRAINT fk_disc_utilisateur FOREIGN KEY (auteur_utilisateur_id) REFERENCES utilisateur(id) ON DELETE SET NULL,
    CONSTRAINT fk_disc_agent FOREIGN KEY (auteur_agent_id) REFERENCES agent(id) ON DELETE SET NULL
);

-- TABLE transfert_eleve
CREATE TABLE transfert_eleve (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eleve_id INT NOT NULL,
    ancienne_classe_id INT,
    nouvelle_classe_id INT,
    ancienne_ecole VARCHAR(200),
    nouvelle_ecole VARCHAR(200),
    date_transfert DATE NOT NULL DEFAULT CURRENT_DATE,
    motif TEXT,
    auteur_id INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_transf_eleve FOREIGN KEY (eleve_id) REFERENCES eleve(id) ON DELETE CASCADE,
    CONSTRAINT fk_transf_ancienne_classe FOREIGN KEY (ancienne_classe_id) REFERENCES classe(id) ON DELETE SET NULL,
    CONSTRAINT fk_transf_nouvelle_classe FOREIGN KEY (nouvelle_classe_id) REFERENCES classe(id) ON DELETE SET NULL,
    CONSTRAINT fk_transf_auteur FOREIGN KEY (auteur_id) REFERENCES utilisateur(id) ON DELETE SET NULL
);

-- TABLE sortie_eleve
CREATE TABLE sortie_eleve (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eleve_id INT NOT NULL,
    annee_scolaire_id INT NOT NULL,
    date_sortie DATE NOT NULL DEFAULT CURRENT_DATE,
    motif VARCHAR(30) NOT NULL CHECK (motif IN ('transfert', 'abandon', 'exclusion', 'fin_cycle', 'deces', 'autre')),
    destination VARCHAR(200),
    observation TEXT,
    auteur_id INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sortie_eleve_annee UNIQUE (eleve_id, annee_scolaire_id),
    CONSTRAINT fk_sortie_eleve FOREIGN KEY (eleve_id) REFERENCES eleve(id) ON DELETE CASCADE,
    CONSTRAINT fk_sortie_annee FOREIGN KEY (annee_scolaire_id) REFERENCES annee_scolaire(id) ON DELETE CASCADE,
    CONSTRAINT fk_sortie_auteur FOREIGN KEY (auteur_id) REFERENCES utilisateur(id) ON DELETE SET NULL
);

-- TABLE categorie_depense
CREATE TABLE categorie_depense (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL UNIQUE,
    actif BOOLEAN NOT NULL DEFAULT TRUE
);

-- TABLE depense
CREATE TABLE depense (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categorie_id INT NOT NULL,
    libelle VARCHAR(200) NOT NULL,
    montant DECIMAL(12,2) NOT NULL CHECK (montant > 0),
    date_depense DATE NOT NULL DEFAULT CURRENT_DATE,
    mode_paiement VARCHAR(30) NOT NULL CHECK (mode_paiement IN ('especes', 'virement', 'cheque', 'mobile_money', 'carte', 'autre')),
    reference VARCHAR(100),
    -- piece_numero : référence comptable séquentielle (ex: DEP-2026-0001), générée via
    -- compteur_recu (voir plus bas) au même titre que paiement.recu_numero — pour que chaque
    -- sortie de caisse soit elle aussi traçable par un numéro de pièce officiel sans trou.
    piece_numero VARCHAR(100) UNIQUE,
    utilisateur_id INT,
    agent_id INT,
    observation TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dep_categorie FOREIGN KEY (categorie_id) REFERENCES categorie_depense(id) ON DELETE RESTRICT,
    CONSTRAINT fk_dep_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur(id) ON DELETE SET NULL,
    CONSTRAINT fk_dep_agent FOREIGN KEY (agent_id) REFERENCES agent(id) ON DELETE SET NULL
);

-- TABLE caisse
CREATE TABLE caisse (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL UNIQUE,
    solde_initial DECIMAL(12,2) NOT NULL DEFAULT 0,
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- TABLE cloture_caisse
-- Arrêté de caisse : à un instant donné, l'agent compte l'argent physiquement présent
-- (solde_reel) et le système compare avec solde_theorique (calculé à partir de solde_initial +
-- tous les mouvements enregistrés jusque-là, même formule que GET /finance/caisses). L'écart
-- est conservé tel quel (jamais corrigé silencieusement) : c'est une pièce d'audit, pas une
-- correction du solde — toute régularisation doit passer par un mouvement_caisse explicite.
CREATE TABLE cloture_caisse (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caisse_id INT NOT NULL,
    date_cloture DATE NOT NULL DEFAULT CURRENT_DATE,
    solde_theorique DECIMAL(12,2) NOT NULL,
    solde_reel DECIMAL(12,2) NOT NULL,
    ecart DECIMAL(12,2) NOT NULL,
    commentaire TEXT,
    utilisateur_id INT,
    agent_id INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cloture_caisse FOREIGN KEY (caisse_id) REFERENCES caisse(id) ON DELETE CASCADE,
    CONSTRAINT fk_cloture_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur(id) ON DELETE SET NULL,
    CONSTRAINT fk_cloture_agent FOREIGN KEY (agent_id) REFERENCES agent(id) ON DELETE SET NULL
);

-- TABLE mouvement_caisse
CREATE TABLE mouvement_caisse (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caisse_id INT NOT NULL,
    type_mouvement VARCHAR(10) NOT NULL CHECK (type_mouvement IN ('entree', 'sortie')),
    montant DECIMAL(12,2) NOT NULL CHECK (montant > 0),
    date_mouvement TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reference VARCHAR(100),
    paiement_id INT,
    depense_id INT,
    utilisateur_id INT,
    -- cloture_id : renseigné rétroactivement quand ce mouvement est inclus dans un arrêté de
    -- caisse (cloture_caisse) — trace quels mouvements ont déjà été vérifiés physiquement,
    -- NULL tant qu'aucune clôture ne les a encore couverts.
    cloture_id INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mouv_caisse FOREIGN KEY (caisse_id) REFERENCES caisse(id) ON DELETE CASCADE,
    CONSTRAINT fk_mouv_paiement FOREIGN KEY (paiement_id) REFERENCES paiement(id) ON DELETE SET NULL,
    CONSTRAINT fk_mouv_depense FOREIGN KEY (depense_id) REFERENCES depense(id) ON DELETE SET NULL,
    CONSTRAINT fk_mouv_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur(id) ON DELETE SET NULL,
    CONSTRAINT fk_mouv_cloture FOREIGN KEY (cloture_id) REFERENCES cloture_caisse(id) ON DELETE SET NULL
);

CREATE INDEX idx_mouvements_caisse_date ON mouvement_caisse(caisse_id, date_mouvement);

-- Vue pratique : solde théorique de chaque caisse.
CREATE OR REPLACE VIEW v_solde_caisse AS
SELECT c.id, c.nom, c.solde_initial,
       c.solde_initial
       + COALESCE(SUM(CASE WHEN m.type_mouvement='entree' THEN m.montant ELSE -m.montant END),0) AS solde_theorique
FROM caisse c
LEFT JOIN mouvement_caisse m ON m.caisse_id = c.id
GROUP BY c.id, c.nom, c.solde_initial;

-- TABLE compteur_recu
-- Compteur atomique pour les numéros de pièce officiels (reçus de paiement, pièces de
-- dépense...), un par (préfixe, année) — ex: ('REC', 2026) -> 0007 donne "REC-2026-0007".
-- L'upsert ON CONFLICT ci-dessous (voir routes/finance.js) est atomique sous PostgreSQL même
-- en cas d'accès concurrent (deux encaissements simultanés au guichet), contrairement à un
-- simple COUNT(*)+1 qui pourrait donner deux fois le même numéro.
CREATE TABLE compteur_recu (
    prefixe VARCHAR(10) NOT NULL,
    annee INT NOT NULL,
    dernier_numero INT NOT NULL DEFAULT 0,
    PRIMARY KEY (prefixe, annee)
);

-- TABLE message_parent
CREATE TABLE message_parent (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id INT NOT NULL,
    eleve_id INT,
    auteur_utilisateur_id INT,
    auteur_agent_id INT,
    sujet VARCHAR(200),
    message TEXT NOT NULL,
    canal VARCHAR(20) NOT NULL DEFAULT 'interne' CHECK (canal IN ('interne', 'email', 'sms', 'les_deux')),
    statut VARCHAR(20) NOT NULL DEFAULT 'envoye' CHECK (statut IN ('brouillon', 'envoye', 'echec', 'lu')),
    date_envoi TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_lecture TIMESTAMPTZ,
    CONSTRAINT fk_msgp_parent FOREIGN KEY (parent_id) REFERENCES parent(id) ON DELETE CASCADE,
    CONSTRAINT fk_msgp_eleve FOREIGN KEY (eleve_id) REFERENCES eleve(id) ON DELETE SET NULL,
    CONSTRAINT fk_msgp_utilisateur FOREIGN KEY (auteur_utilisateur_id) REFERENCES utilisateur(id) ON DELETE SET NULL,
    CONSTRAINT fk_msgp_agent FOREIGN KEY (auteur_agent_id) REFERENCES agent(id) ON DELETE SET NULL
);

-- TABLE audit_log
CREATE TABLE audit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id INT,
    agent_id INT,
    action VARCHAR(20) NOT NULL CHECK (action IN ('creation', 'modification', 'suppression', 'connexion', 'autre')),
    table_nom VARCHAR(100) NOT NULL,
    record_id INT,
    ancienne_valeur JSONB,
    nouvelle_valeur JSONB,
    date_action TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(45),
    CONSTRAINT fk_audit_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur(id) ON DELETE SET NULL,
    CONSTRAINT fk_audit_agent FOREIGN KEY (agent_id) REFERENCES agent(id) ON DELETE SET NULL
);

-- TABLE assistant_conversation : historique du chat de l'assistant IA (admin uniquement).
-- Ne stocke que le texte visible (role + content) — jamais le détail des appels d'outils.
CREATE TABLE assistant_conversation (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id INT NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_assistant_conv_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur(id) ON DELETE CASCADE
);
CREATE INDEX idx_assistant_conv_utilisateur ON assistant_conversation(utilisateur_id, created_at);


-- ============================================================
-- CONTRAINTES MÉTIER + INDEX + VALIDATIONS
-- ============================================================

-- Cohérence des affectations enseignant/matière/classe/année.
ALTER TABLE emploi_du_temps
    ADD CONSTRAINT fk_edt_assignment
    FOREIGN KEY (enseignant_id, matiere_id, classe_id, annee_scolaire_id)
    REFERENCES enseignant_matiere_classe(enseignant_id, matiere_id, classe_id, annee_scolaire_id)
    ON DELETE RESTRICT;

ALTER TABLE devoir
    ADD CONSTRAINT fk_devoir_assignment
    FOREIGN KEY (enseignant_id, matiere_id, classe_id, annee_scolaire_id)
    REFERENCES enseignant_matiere_classe(enseignant_id, matiere_id, classe_id, annee_scolaire_id)
    ON DELETE RESTRICT;

-- examen_matiere porte le contexte classe/année pour sécuriser l'affectation du professeur.
ALTER TABLE examen_matiere
    ADD COLUMN classe_id INT,
    ADD COLUMN annee_scolaire_id INT;

UPDATE examen_matiere em
SET classe_id = e.classe_id,
    annee_scolaire_id = e.annee_scolaire_id
FROM examen e
WHERE e.id = em.examen_id;

ALTER TABLE examen_matiere
    ALTER COLUMN classe_id SET NOT NULL,
    ALTER COLUMN annee_scolaire_id SET NOT NULL;

ALTER TABLE examen_matiere
    ADD CONSTRAINT fk_exm_classe FOREIGN KEY (classe_id) REFERENCES classe(id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_exm_annee FOREIGN KEY (annee_scolaire_id) REFERENCES annee_scolaire(id) ON DELETE RESTRICT,
    ADD CONSTRAINT fk_exm_assignment
      FOREIGN KEY (enseignant_id, matiere_id, classe_id, annee_scolaire_id)
      REFERENCES enseignant_matiere_classe(enseignant_id, matiere_id, classe_id, annee_scolaire_id)
      ON DELETE RESTRICT;

-- Paiement : l'élève doit être le même que celui du frais concerné.
ALTER TABLE frais_scolaire
    ADD CONSTRAINT uk_frais_id_eleve UNIQUE (id, eleve_id);

ALTER TABLE paiement
    ADD CONSTRAINT fk_paiement_frais_eleve
    FOREIGN KEY (frais_id, eleve_id) REFERENCES frais_scolaire(id, eleve_id) ON DELETE CASCADE;

-- Empêche les doublons de numéro d'élève quand le numéro est renseigné.
CREATE UNIQUE INDEX uk_inscription_classe_numero
    ON inscription(classe_id, annee_scolaire_id, numero_classe)
    WHERE numero_classe IS NOT NULL;

-- Un même frais mensuel ne peut exister qu'une fois (voir version affinée
-- uk_frais_eleve_type_mois_annee plus bas, qui remplace cet index : elle
-- exclut les frais 'annule' pour permettre de refacturer un mois annulé).

-- Cohérence des bulletins/notes avec le bimestre et l'année scolaire.
ALTER TABLE bulletin
    ADD CONSTRAINT fk_bul_bimestre_annee
    FOREIGN KEY (bimestre_id, annee_scolaire_id) REFERENCES bimestre(id, annee_scolaire_id) ON DELETE RESTRICT;

ALTER TABLE note
    ADD CONSTRAINT fk_note_bimestre_annee
    FOREIGN KEY (bimestre_id, annee_scolaire_id) REFERENCES bimestre(id, annee_scolaire_id) ON DELETE RESTRICT;

-- Un type d'évaluation explicite évite les doublons NULL dans les règles d'unicité métier.
ALTER TABLE note
    ALTER COLUMN type_evaluation SET DEFAULT 'autre',
    ALTER COLUMN type_evaluation SET NOT NULL;

CREATE UNIQUE INDEX uk_note_eleve_matiere_bimestre_type
    ON note(eleve_id, matiere_id, bimestre_id, type_evaluation);

-- Contrôle des horaires de l'EDT : aucun chevauchement pour une classe
-- ou un enseignant dans la même année scolaire.
CREATE OR REPLACE FUNCTION fn_check_edt_overlap()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM emploi_du_temps e
        WHERE e.id <> COALESCE(NEW.id, 0)
          AND e.actif = TRUE
          AND NEW.actif = TRUE
          AND e.annee_scolaire_id = NEW.annee_scolaire_id
          AND e.jour = NEW.jour
          AND (
              (e.classe_id = NEW.classe_id AND e.matiere_id = NEW.matiere_id)
              OR (
                  (
                      e.classe_id = NEW.classe_id
                      OR e.enseignant_id = NEW.enseignant_id
                      OR (NEW.salle_id IS NOT NULL AND e.salle_id = NEW.salle_id)
                  )
                  AND NEW.heure_debut < e.heure_fin
                  AND NEW.heure_fin > e.heure_debut
              )
          )
    ) THEN
        RAISE EXCEPTION 'Chevauchement emploi du temps: classe ou enseignant déjà occupé (%) %-%',
            NEW.jour, NEW.heure_debut, NEW.heure_fin;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_edt_no_overlap
BEFORE INSERT OR UPDATE ON emploi_du_temps
FOR EACH ROW EXECUTE FUNCTION fn_check_edt_overlap();

CREATE INDEX idx_edt_salle_jour
  ON emploi_du_temps(salle_id, annee_scolaire_id, jour, heure_debut, heure_fin)
  WHERE actif = TRUE;

-- Vérifie que le paiement ne dépasse pas le montant du frais.
CREATE OR REPLACE FUNCTION fn_check_paiement_montant()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    total_paye NUMERIC(12,2);
    montant_frais NUMERIC(12,2);
BEGIN
    SELECT montant_total INTO montant_frais
    FROM frais_scolaire
    WHERE id = NEW.frais_id;

    SELECT COALESCE(SUM(p.montant), 0) INTO total_paye
    FROM paiement p
    WHERE p.frais_id = NEW.frais_id
      AND p.id <> COALESCE(NEW.id, 0);

    IF total_paye + NEW.montant > montant_frais THEN
        RAISE EXCEPTION 'Paiement supérieur au montant du frais: frais %, montant %, déjà payé %',
            NEW.frais_id, montant_frais, total_paye;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_paiement_montant
BEFORE INSERT OR UPDATE ON paiement
FOR EACH ROW EXECUTE FUNCTION fn_check_paiement_montant();

CREATE INDEX idx_edt_classe_jour ON emploi_du_temps(classe_id, annee_scolaire_id, jour, heure_debut, heure_fin);
CREATE INDEX idx_edt_enseignant_jour ON emploi_du_temps(enseignant_id, annee_scolaire_id, jour, heure_debut, heure_fin);
CREATE INDEX idx_note_assignment ON note(enseignant_id, matiere_id, classe_id, annee_scolaire_id);
CREATE INDEX idx_pointage_eleve_context ON pointage_eleve(eleve_id, classe_id, annee_scolaire_id, date_pointage);
CREATE INDEX idx_paiement_frais ON paiement(frais_id, date_paiement);
CREATE INDEX idx_bulletin_eleve_annee ON bulletin(eleve_id, annee_scolaire_id, bimestre_id);
CREATE INDEX idx_pointage_ens_validation ON pointage_enseignant(statut_validation) WHERE statut_validation = 'en_attente_validation';
CREATE INDEX idx_pointage_ens_date ON pointage_enseignant(date_pointage, enseignant_id);
-- pointage_enseignant.emploi_du_temps_id (utilisé par presenceCron.js pour le lot de cours du
-- jour expirés — WHERE date_pointage = $1 AND emploi_du_temps_id = ANY($2)) : la contrainte
-- UNIQUE (enseignant_id, emploi_du_temps_id, date_pointage) crée déjà un index sur ces 3
-- colonnes DANS CET ORDRE, inutilisable pour un filtre sur emploi_du_temps_id seul. Index dédié :
CREATE INDEX idx_pointage_ens_edt_date ON pointage_enseignant(emploi_du_temps_id, date_pointage);

-- Index supplémentaires (routes/statistiques.js, routes/historique.js, services/relanceService.js,
-- services/presenceCron.js) : ces modules filtrent régulièrement par plage de dates seule, ou par
-- "auteur" (enseignant_id/agent_id/utilisateur_id) + plage de dates, sur des tables où seul un
-- index (eleve_id, ...) ou (frais_id, ...) existait déjà — inutile pour ce type de requête (leur
-- colonne de tête n'est pas celle filtrée). Index partiels sur les colonnes "auteur" nullables :
-- plus compacts, et Postgres les ignore de toute façon pour les lignes où la colonne est NULL.
CREATE INDEX idx_pointage_eleve_date ON pointage_eleve(date_pointage);
CREATE INDEX idx_pointage_eleve_enseignant_date ON pointage_eleve(enseignant_id, date_pointage);
CREATE INDEX idx_pointage_eleve_agent_date ON pointage_eleve(agent_id, date_pointage) WHERE agent_id IS NOT NULL;

CREATE INDEX idx_note_created_at ON note(created_at);

CREATE INDEX idx_discipline_date ON discipline(date_incident);
CREATE INDEX idx_discipline_auteur_utilisateur ON discipline(auteur_utilisateur_id, date_incident) WHERE auteur_utilisateur_id IS NOT NULL;
CREATE INDEX idx_discipline_auteur_agent ON discipline(auteur_agent_id, date_incident) WHERE auteur_agent_id IS NOT NULL;

CREATE INDEX idx_absence_eleve_date ON absence_eleve(date_absence);
CREATE INDEX idx_absence_eleve_auteur_utilisateur ON absence_eleve(auteur_utilisateur_id, date_absence) WHERE auteur_utilisateur_id IS NOT NULL;
CREATE INDEX idx_absence_eleve_auteur_agent ON absence_eleve(auteur_agent_id, date_absence) WHERE auteur_agent_id IS NOT NULL;

CREATE INDEX idx_absence_enseignant_date ON absence_enseignant(date_absence);
CREATE INDEX idx_absence_enseignant_auteur_utilisateur ON absence_enseignant(auteur_utilisateur_id, date_absence) WHERE auteur_utilisateur_id IS NOT NULL;
CREATE INDEX idx_absence_enseignant_auteur_agent ON absence_enseignant(auteur_agent_id, date_absence) WHERE auteur_agent_id IS NOT NULL;
-- presenceCron.js : SELECT ... FROM absence_enseignant WHERE date_absence = $1 AND emploi_du_temps_id = ANY($2)
CREATE INDEX idx_absence_enseignant_edt_date ON absence_enseignant(emploi_du_temps_id, date_absence);

CREATE INDEX idx_paiement_date ON paiement(date_paiement);
CREATE INDEX idx_paiement_utilisateur_date ON paiement(utilisateur_id, date_paiement) WHERE utilisateur_id IS NOT NULL;
CREATE INDEX idx_paiement_agent_date ON paiement(agent_id, date_paiement) WHERE agent_id IS NOT NULL;

CREATE INDEX idx_depense_date ON depense(date_depense);
CREATE INDEX idx_depense_utilisateur_date ON depense(utilisateur_id, date_depense) WHERE utilisateur_id IS NOT NULL;
CREATE INDEX idx_depense_agent_date ON depense(agent_id, date_depense) WHERE agent_id IS NOT NULL;

-- services/relanceService.js : candidats à relancer = frais impaye/partiel avec échéance dépassée.
-- Index partiel calé exactement sur le WHERE de la requête (statut IN ('impaye','partiel') AND
-- date_echeance <= ...) : ne référence que les lignes réellement susceptibles d'être candidates
-- (un frais 'paye'/'annule' n'y figure jamais), donc beaucoup plus petit qu'un index plein sur
-- toute la table frais_scolaire.
CREATE INDEX idx_frais_scolaire_relance ON frais_scolaire(date_echeance) WHERE statut IN ('impaye', 'partiel');

-- services/relanceService.js : lookup du parent responsable principal, désormais fait pour un lot
-- entier d'élèves en une seule requête (WHERE ep.eleve_id = ANY($1) AND responsable_principal).
-- Index partiel : une ligne par élève au maximum (au plus un responsable_principal), donc compact.
CREATE INDEX idx_eleve_parent_responsable ON eleve_parent(eleve_id) WHERE responsable_principal = TRUE;

-- Mise à jour automatique des colonnes updated_at.
CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_utilisateur_updated_at BEFORE UPDATE ON utilisateur
FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
CREATE TRIGGER trg_agent_updated_at BEFORE UPDATE ON agent
FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
CREATE TRIGGER trg_eleve_updated_at BEFORE UPDATE ON eleve
FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
CREATE TRIGGER trg_parent_updated_at BEFORE UPDATE ON parent
FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
CREATE TRIGGER trg_actualite_updated_at BEFORE UPDATE ON actualite
FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();

-- Contraintes métier supplémentaires
CREATE UNIQUE INDEX uk_annee_scolaire_active ON annee_scolaire((actif)) WHERE actif = TRUE;
CREATE UNIQUE INDEX uk_parent_responsable_principal ON eleve_parent(eleve_id) WHERE responsable_principal = TRUE;
CREATE UNIQUE INDEX uk_inscription_active_eleve_annee ON inscription(eleve_id, annee_scolaire_id) WHERE statut = 'inscrit';

CREATE OR REPLACE FUNCTION fn_immutable_official_record()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'Enregistrement officiel immuable : utilisez une procédure corrective tracée.';
END;
$$;
CREATE TRIGGER trg_certificat_immutable BEFORE UPDATE OR DELETE ON certificat_scolarite FOR EACH ROW EXECUTE FUNCTION fn_immutable_official_record();

CREATE OR REPLACE FUNCTION fn_audit_append_only()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'Le journal d''audit est en lecture seule.';
END;
$$;
CREATE TRIGGER trg_audit_append_only BEFORE UPDATE OR DELETE ON audit_log FOR EACH ROW EXECUTE FUNCTION fn_audit_append_only();

-- Les permissions et leurs affectations initiales sont fournies par database/seed.sql.


-- ============================================================
-- ATTENTION : ce fichier DROP puis recrée toutes les tables (voir
-- DROP TABLE ... CASCADE en haut) : l'exécuter EFFACE toutes les données
-- existantes. À réserver à une installation neuve, ou à une refonte
-- complète assumée d'une base existante.
-- ============================================================


-- ============================================================
-- V10 FINAL : sécurité, communications, sauvegardes et observabilité
-- Ces éléments proviennent des anciennes migrations et sont désormais
-- intégrés directement au schéma canonique.
-- ============================================================

CREATE TABLE password_reset_token (
  id BIGSERIAL PRIMARY KEY,
  subject_type VARCHAR(20) NOT NULL CHECK (subject_type IN ('utilisateur','agent')),
  subject_id INT NOT NULL,
  token_hash CHAR(64) NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  requested_ip INET,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_password_reset_subject ON password_reset_token(subject_type, subject_id);
CREATE INDEX idx_password_reset_expiry ON password_reset_token(expires_at);

CREATE TABLE notification_delivery (
  id BIGSERIAL PRIMARY KEY,
  notification_id INT REFERENCES notification(id) ON DELETE CASCADE,
  message_parent_id INT REFERENCES message_parent(id) ON DELETE CASCADE,
  channel VARCHAR(20) NOT NULL CHECK (channel IN ('email','whatsapp')),
  destination VARCHAR(255),
  status VARCHAR(30) NOT NULL,
  provider_id VARCHAR(255),
  error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_notification_delivery_created ON notification_delivery(created_at DESC);

CREATE TABLE security_event (
  id BIGSERIAL PRIMARY KEY,
  subject_type VARCHAR(20),
  subject_id INT,
  event_type VARCHAR(80) NOT NULL,
  ip INET,
  user_agent TEXT,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_security_event_created ON security_event(created_at DESC);


CREATE TABLE communication_usage (
  id BIGSERIAL PRIMARY KEY,
  channel VARCHAR(20) NOT NULL CHECK (channel IN ('email','whatsapp')),
  usage_date DATE NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  UNIQUE(channel, usage_date)
);
CREATE INDEX idx_communication_usage_date ON communication_usage(usage_date DESC);

CREATE TABLE system_backup (
  id BIGSERIAL PRIMARY KEY,
  filename VARCHAR(255) NOT NULL,
  filepath TEXT NOT NULL,
  size_bytes BIGINT,
  checksum_sha256 CHAR(64),
  created_by_utilisateur_id INT REFERENCES utilisateur(id) ON DELETE SET NULL,
  created_by_agent_id INT REFERENCES agent(id) ON DELETE SET NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'success' CHECK (status IN ('success','failed')),
  error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_system_backup_created ON system_backup(created_at DESC);



-- V12 PRO — Finance integrity upgrade (fusionné depuis database/migrations/V12_PRO_FINANCE_INTEGRITY.sql)
-- Un paiement doit toujours concerner le même élève que le frais.
CREATE OR REPLACE FUNCTION fn_verifier_paiement_eleve()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE frais_eleve INT;
BEGIN
  SELECT eleve_id INTO frais_eleve FROM frais_scolaire WHERE id = NEW.frais_id;
  IF frais_eleve IS NULL THEN RAISE EXCEPTION 'Frais scolaire introuvable.'; END IF;
  IF NEW.eleve_id <> frais_eleve THEN RAISE EXCEPTION 'Le paiement doit appartenir au même élève que le frais.'; END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_verifier_paiement_eleve ON paiement;
CREATE TRIGGER trg_verifier_paiement_eleve BEFORE INSERT OR UPDATE ON paiement
FOR EACH ROW EXECUTE FUNCTION fn_verifier_paiement_eleve();

-- Un mouvement ne peut être simultanément lié à un paiement et à une dépense.
CREATE OR REPLACE FUNCTION fn_verifier_mouvement_source()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.paiement_id IS NOT NULL AND NEW.depense_id IS NOT NULL THEN
    RAISE EXCEPTION 'Un mouvement de caisse ne peut référencer simultanément un paiement et une dépense.';
  END IF;
  IF NEW.paiement_id IS NULL AND NEW.depense_id IS NULL THEN
    RAISE EXCEPTION 'Un mouvement de caisse doit être rattaché à une pièce source.';
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_verifier_mouvement_source ON mouvement_caisse;
CREATE TRIGGER trg_verifier_mouvement_source BEFORE INSERT OR UPDATE ON mouvement_caisse
FOR EACH ROW EXECUTE FUNCTION fn_verifier_mouvement_source();

-- Un frais récurrent mensuel ne peut avoir deux lignes pour le même élève/mois/année/type.
CREATE UNIQUE INDEX IF NOT EXISTS uk_frais_eleve_type_mois_annee
ON frais_scolaire(eleve_id, annee_scolaire_id, type_frais, mois)
WHERE mois IS NOT NULL AND statut <> 'annule';

CREATE INDEX IF NOT EXISTS idx_frais_eleve_statut_echeance
ON frais_scolaire(eleve_id, statut, date_echeance);
CREATE INDEX IF NOT EXISTS idx_paiement_eleve_date
ON paiement(eleve_id, date_paiement DESC);
CREATE INDEX IF NOT EXISTS idx_depense_date_categorie
ON depense(date_depense DESC, categorie_id);
CREATE INDEX IF NOT EXISTS idx_mouvement_caisse_uncloture
ON mouvement_caisse(caisse_id, date_mouvement DESC) WHERE cloture_id IS NULL;

-- V12 PRO : intégrité des paiements. Un frais ne peut jamais être surpayé.
CREATE OR REPLACE FUNCTION fn_verifier_paiement_montant()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE total_existant NUMERIC(12,2);
        montant_frais NUMERIC(12,2);
BEGIN
  SELECT montant_total INTO montant_frais FROM frais_scolaire WHERE id = NEW.frais_id FOR UPDATE;
  IF montant_frais IS NULL THEN RAISE EXCEPTION 'Frais scolaire introuvable.'; END IF;
  SELECT COALESCE(SUM(montant),0) INTO total_existant FROM paiement WHERE frais_id = NEW.frais_id AND id <> COALESCE(NEW.id,0);
  IF total_existant + NEW.montant > montant_frais THEN
    RAISE EXCEPTION 'Paiement refusé : montant supérieur au solde restant dû.';
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_verifier_paiement_montant ON paiement;
CREATE TRIGGER trg_verifier_paiement_montant BEFORE INSERT OR UPDATE ON paiement
FOR EACH ROW EXECUTE FUNCTION fn_verifier_paiement_montant();

-- ============================================================
-- COPEC OFFLINE / ONLINE SYNC LAYER (fusionné depuis database/sync/sync-schema.sql)
-- Garde la base métier intacte et ajoute uniquement la traçabilité nécessaire
-- à la synchronisation bidirectionnelle (serveur local <-> Neon).
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS sync_device (
    id BIGSERIAL PRIMARY KEY,
    device_id VARCHAR(100) NOT NULL UNIQUE,
    nom VARCHAR(150),
    type VARCHAR(20) NOT NULL DEFAULT 'local-server' CHECK (type IN ('local-server','central-server')),
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    last_seen_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sync_change (
    id BIGSERIAL PRIMARY KEY,
    operation_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    source_device_id VARCHAR(100) NOT NULL,
    table_name VARCHAR(120) NOT NULL,
    operation VARCHAR(10) NOT NULL CHECK (operation IN ('INSERT','UPDATE','DELETE')),
    row_key JSONB NOT NULL,
    old_row JSONB,
    new_row JSONB,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sync_change_id ON sync_change(id);
CREATE INDEX IF NOT EXISTS idx_sync_change_table ON sync_change(table_name, id);
CREATE INDEX IF NOT EXISTS idx_sync_change_device ON sync_change(source_device_id, id);

CREATE TABLE IF NOT EXISTS sync_conflict (
    id BIGSERIAL PRIMARY KEY,
    operation_id UUID NOT NULL,
    source_device_id VARCHAR(100) NOT NULL,
    table_name VARCHAR(120) NOT NULL,
    row_key JSONB NOT NULL,
    local_row JSONB,
    incoming_row JSONB,
    reason TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','resolved','ignored')),
    resolution VARCHAR(20) CHECK (resolution IN ('local','incoming','manual')),
    resolved_by BIGINT,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sync_conflict_status ON sync_conflict(status, created_at DESC);

CREATE TABLE IF NOT EXISTS sync_state (
    singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
    last_pushed_local_change_id BIGINT NOT NULL DEFAULT 0,
    last_pulled_central_change_id BIGINT NOT NULL DEFAULT 0,
    last_success_at TIMESTAMPTZ,
    last_attempt_at TIMESTAMPTZ,
    last_error TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'idle' CHECK (status IN ('idle','syncing','offline','error'))
);
INSERT INTO sync_state(singleton) VALUES(TRUE) ON CONFLICT (singleton) DO NOTHING;

-- Retourne la clé primaire sous forme JSON, y compris pour les tables à PK composite.
CREATE OR REPLACE FUNCTION copec_sync_pk_json(p_table REGCLASS, p_row JSONB)
RETURNS JSONB
LANGUAGE SQL
STABLE
AS $$
    SELECT COALESCE(jsonb_object_agg(a.attname, p_row -> a.attname), '{}'::jsonb)
    FROM pg_index i
    JOIN pg_attribute a
      ON a.attrelid = i.indrelid
     AND a.attnum = ANY(i.indkey)
    WHERE i.indrelid = p_table
      AND i.indisprimary;
$$;

CREATE OR REPLACE FUNCTION copec_sync_capture()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_old JSONB;
    v_new JSONB;
    v_key JSONB;
    v_device TEXT;
BEGIN
    -- Les applications de changements distants utilisent ce flag afin de ne pas
    -- créer une boucle de réplication infinie.
    IF current_setting('copec.sync_apply', true) = 'true' THEN
        RETURN COALESCE(NEW, OLD);
    END IF;

    -- Tables techniques de synchronisation : jamais journalisées par elles-mêmes.
    IF TG_TABLE_NAME IN ('sync_change','sync_device','sync_conflict','sync_state') THEN
        RETURN COALESCE(NEW, OLD);
    END IF;

    v_old := CASE WHEN TG_OP IN ('UPDATE','DELETE') THEN to_jsonb(OLD) END;
    v_new := CASE WHEN TG_OP IN ('INSERT','UPDATE') THEN to_jsonb(NEW) END;
    v_key := copec_sync_pk_json(TG_RELID, COALESCE(v_new, v_old));
    v_device := COALESCE(current_setting('copec.sync_device', true), 'unknown');

    INSERT INTO sync_change(source_device_id, table_name, operation, row_key, old_row, new_row)
    VALUES (v_device, TG_TABLE_NAME, TG_OP, v_key, v_old, v_new);

    RETURN COALESCE(NEW, OLD);
END;
$$;

-- NOTE : le trigger trg_copec_sync (qui journalise chaque écriture dans sync_change)
-- est installé à la fin de database/seed.sql, une fois les données de démo chargées —
-- pas ici — pour que le jeu de données seed ne pollue pas sync_change dès le départ
-- (même ordre que l'ancien database/sync/sync-schema.sql, qui s'appliquait après seed.sql).

COMMIT;
